export const ACTIVE_TAB = 'ACTIVE_TAB';
export const ACTIVE_COLOR = 'ACTIVE_COLOR';
export const ACTIVE_BACKGROUND_SIDEBAR = 'ACTIVE_BACKGROUND_SIDEBAR';
export const ACTIVE_PAGE = 'ACTIVE_PAGE';
export const TOGGLE_SIDEBAR = 'TOOGLE_SIDEBAR';